Missing escape string on addToDB and updateInDB
Missing use of $DB->escape($this->fields[$field]) on addToDB and updateInDB.
Code should be modified to use $DB->escape function as of other function on `commondbtm.class.php` file.

```
 $query .= "'".$DB->escape($values[$i])."'";
```

Sample error :
```
  SQL: INSERT
                   INTO `glpi_plugin_fields_labeltranslations` (`plugin_fields_itemtype`,`plugin_fields_items_id`,`language`,`label`) VALUES (\'PluginFieldsContainer\',\'3\',\'en_GB\',\'Alex\'s fields\')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's fields')' at line 2
  Backtrace :
  inc\commondbtm.class.php:436                       
  inc\commondbtm.class.php:852                       CommonDBTM->addToDB()
  plugins\fields\inc\labeltranslation.class.php:64   CommonDBTM->add()
  plugins\fields\inc\container.class.php:300         PluginFieldsLabelTranslation::createForItem()
  plugins\fields\hook.php:159                        PluginFieldsContainer->post_addItem()
  plugins\fields\front\regenerate_files.php:7        regenerateFiles()
```